# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transporte_interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 409)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.txtOrigenes = QtWidgets.QLineEdit(Dialog)
        self.txtOrigenes.setMaximumSize(QtCore.QSize(250, 16777215))
        self.txtOrigenes.setObjectName("txtOrigenes")
        self.verticalLayout_2.addWidget(self.txtOrigenes)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.cbxMax_min = QtWidgets.QComboBox(Dialog)
        self.cbxMax_min.setMinimumSize(QtCore.QSize(100, 0))
        self.cbxMax_min.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbxMax_min.setObjectName("cbxMax_min")
        self.cbxMax_min.addItem("")
        self.cbxMax_min.addItem("")
        self.verticalLayout_3.addWidget(self.cbxMax_min)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtDestinos = QtWidgets.QLineEdit(Dialog)
        self.txtDestinos.setMaximumSize(QtCore.QSize(250, 16777215))
        self.txtDestinos.setObjectName("txtDestinos")
        self.verticalLayout.addWidget(self.txtDestinos)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 250))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 525, 248))
        self.scrollContent.setObjectName("scrollContent")
        self.layoutWidget = QtWidgets.QWidget(self.scrollContent)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 527, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridData = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridData.setContentsMargins(10, 10, 10, 10)
        self.gridData.setObjectName("gridData")
        self.scrollArea.setWidget(self.scrollContent)
        self.gridLayout.addWidget(self.scrollArea, 8, 0, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnClose = QtWidgets.QPushButton(Dialog)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.btnLimpiar = QtWidgets.QPushButton(Dialog)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.horizontalLayout_2.addWidget(self.btnLimpiar)
        self.btnSolve = QtWidgets.QPushButton(Dialog)
        self.btnSolve.setObjectName("btnSolve")
        self.horizontalLayout_2.addWidget(self.btnSolve)
        self.gridLayout.addLayout(self.horizontalLayout_2, 14, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtOrigenes, self.txtDestinos)
        Dialog.setTabOrder(self.txtDestinos, self.btnSolve)
        Dialog.setTabOrder(self.btnSolve, self.btnClose)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Métodos de Solución de Problemas de Transporte"))
        self.label_2.setText(_translate("Dialog", "Cantidad de Origenes"))
        self.cbxMax_min.setItemText(0, _translate("Dialog", "Minimizar"))
        self.cbxMax_min.setItemText(1, _translate("Dialog", "Maximizar"))
        self.label.setText(_translate("Dialog", "Cantidad de Destinos"))
        self.label_4.setText(_translate("Dialog", "Coeficientes"))
        self.btnClose.setText(_translate("Dialog", "Cerrar"))
        self.btnLimpiar.setText(_translate("Dialog", "Limpiar"))
        self.btnSolve.setText(_translate("Dialog", "Resolver"))

